# Generated by Django 3.2.3 on 2021-05-15 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("fill_priority", models.IntegerField()),
                ("motocycle_spaces", models.IntegerField()),
                ("car_spaces", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Princing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_coefficient", models.IntegerField()),
                ("b_coefficient", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_type", models.CharField(max_length=50)),
                ("license_plate", models.CharField(max_length=10)),
                ("arrived_at", models.DateTimeField()),
                ("paid_at", models.DateTimeField(default=None)),
                ("amount_paid", models.IntegerField()),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="park.level"
                    ),
                ),
            ],
        ),
    ]
