# Generated by Django 3.2.3 on 2021-05-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='amount_paid',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='paid_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
