# Generated by Django 3.2.3 on 2021-05-18 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0003_rename_motocycle_spaces_level_motorcycle_spaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='space',
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('vehicle_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='park.vehicle')),
                ('level_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.level')),
            ],
        ),
    ]
