# Generated by Django 3.2.3 on 2021-05-20 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0004_auto_20210518_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='level_set',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='vehicle_set',
            new_name='vehicle',
        ),
    ]
