# Generated by Django 3.2.3 on 2021-05-21 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0005_auto_20210520_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Space',
        ),
    ]
