# Generated by Django 3.2.3 on 2021-05-21 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0006_delete_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.level')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='park.vehicle')),
            ],
        ),
    ]
