# Generated by Django 3.2.3 on 2021-05-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0010_auto_20210521_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
