# Generated by Django 3.2.3 on 2021-05-21 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0011_auto_20210521_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=10)),
                ('arrived_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('amount_paid', models.IntegerField(blank=True, default=None, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.level')),
            ],
        ),
        migrations.DeleteModel(
            name='Space',
        ),
    ]
