# Generated by Django 3.2.3 on 2021-05-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0013_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='park.vehicle'),
        ),
    ]
