# Generated by Django 3.2.3 on 2021-05-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0014_alter_space_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='space',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='park.space'),
        ),
    ]
